"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function RegisterPage() {
  const router = useRouter();

  // STATE BARU: Untuk nyimpen posisi user lagi di step berapa (1, 2, atau 3)
  const [step, setStep] = useState(1);

  const [formData, setFormData] = useState({
    fullName: "",
    primaryEmail: "",
    otherEmail: "",
    institutionEmail: "",
    contactNumber: "",
    otherContactNumber: "",
    institutionName: "",
    institutionType: "university",
    institutionAddress: "",
    annualFee: 458000,
    coffeeContribution: "0",
    paymentMethod: "BNI virtual account",
  });

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >,
  ) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Fungsi buat pindah step
  const nextStep = () => setStep((prev) => prev + 1);
  const prevStep = () => setStep((prev) => prev - 1);

  // Fungsi pas tombol final di step 3 diklik
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const autoGeneratedPassword = Math.random().toString(36).slice(-8);
    const payload = {
      full_name: formData.fullName,
      email_primary: formData.primaryEmail,
      email_other: formData.otherEmail,
      email_institution: formData.institutionEmail,
      phone_primary: formData.contactNumber,
      phone_other: formData.otherContactNumber,
      password: autoGeneratedPassword,
      institution_name: formData.institutionName,
      institution_type: formData.institutionType,
      address: formData.institutionAddress,
      payment_method: formData.paymentMethod,
      coffee_contribution:
        parseInt(formData.coffeeContribution.replace("k", "000")) || 0,
    };

    try {
      const response = await fetch("http://localhost:3000/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const result = await response.json();

      if (response.ok) {
        alert("Registrasi berhasil! Beralih ke halaman pembayaran...");
        router.push("/register/payment");
      } else {
        alert(`Gagal: ${result.message || "Cek kembali data kamu"}`);
      }
    } catch (error) {
      console.error("Gagal registrasi:", error);
      alert("Gagal menyambung ke server Backend!");
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-8 bg-white shadow-lg rounded-lg my-10 font-sans">
      <h1 className="text-3xl font-bold text-center text-orange-500 mb-2">
        Registration
      </h1>
      <p className="text-center text-gray-600 mb-8">
        Create your account, it takes less than a minute.
      </p>

      {/* STEPPER UI: Indikator Step di Atas */}
      <div className="flex justify-center items-center mb-8 bg-gray-100 rounded-full p-1 text-sm md:text-base">
        <div
          className={`flex-1 text-center py-2 rounded-full transition-colors ${step === 1 ? "bg-orange-400 text-white font-bold shadow" : "text-gray-500"}`}
        >
          1 Account Information
        </div>
        <div
          className={`flex-1 text-center py-2 rounded-full transition-colors ${step === 2 ? "bg-orange-400 text-white font-bold shadow" : "text-gray-500"}`}
        >
          2 Institution Information
        </div>
        <div
          className={`flex-1 text-center py-2 rounded-full transition-colors ${step === 3 ? "bg-orange-400 text-white font-bold shadow" : "text-gray-500"}`}
        >
          3 Annual Fee
        </div>
      </div>

      {/* FORM: Pindah handler onSubmit tergantung lagi di step berapa */}
      <form
        onSubmit={
          step === 3
            ? handleSubmit
            : (e) => {
                e.preventDefault();
                nextStep();
              }
        }
        className="space-y-6"
      >
        {/* ======== STEP 1: ACCOUNT INFORMATION ======== */}
        {step === 1 && (
          <div className="animate-fade-in">
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Full Name / Nama Lengkap *
                </label>
                <input
                  name="fullName"
                  value={formData.fullName}
                  onChange={handleChange}
                  placeholder="Input your full name"
                  className="border p-3 rounded w-full"
                  required
                  minLength={3}
                />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Primary Email Address *
                </label>
                <input
                  name="primaryEmail"
                  value={formData.primaryEmail}
                  onChange={handleChange}
                  placeholder="Input your primary email address"
                  className="border p-3 rounded w-full"
                  required
                  type="email"
                />
                <p className="text-xs text-orange-500 mt-1">
                  * Primary email for account as username.
                </p>
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Other Email Address
                </label>
                <input
                  name="otherEmail"
                  value={formData.otherEmail}
                  onChange={handleChange}
                  placeholder="Input your other email address"
                  className="border p-3 rounded w-full"
                  type="email"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Institution Email Address *
                </label>
                <input
                  name="institutionEmail"
                  value={formData.institutionEmail}
                  onChange={handleChange}
                  placeholder="Input your institution email address"
                  className="border p-3 rounded w-full"
                  required
                  type="email"
                />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-1">
                    Contact Number *
                  </label>
                  <input
                    name="contactNumber"
                    value={formData.contactNumber}
                    onChange={handleChange}
                    placeholder="Min 13 Digits"
                    className="border p-3 rounded w-full"
                    required
                    minLength={13}
                    maxLength={15}
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1">
                    Other Contact
                  </label>
                  <input
                    name="otherContactNumber"
                    value={formData.otherContactNumber}
                    onChange={handleChange}
                    placeholder="Optional"
                    className="border p-3 rounded w-full"
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ======== STEP 2: INSTITUTION INFORMATION ======== */}
        {step === 2 && (
          <div className="animate-fade-in">
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Institution Name *
                </label>
                <input
                  name="institutionName"
                  value={formData.institutionName}
                  onChange={handleChange}
                  placeholder="Institution Name"
                  className="border p-3 rounded w-full"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Institution Type *
                </label>
                <select
                  name="institutionType"
                  value={formData.institutionType}
                  onChange={handleChange}
                  className="border p-3 rounded w-full bg-white"
                >
                  <option value="university">University</option>
                  <option value="society">Society</option>
                  <option value="government agency">Government Agency</option>
                  <option value="publisher (education)">
                    Publisher (Education)
                  </option>
                  <option value="foundation">Foundation</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1">
                  Institution Address *
                </label>
                <textarea
                  name="institutionAddress"
                  value={formData.institutionAddress}
                  onChange={handleChange}
                  placeholder="Complete Address"
                  className="border p-3 rounded w-full"
                  rows={4}
                  required
                />
              </div>
            </div>
          </div>
        )}

        {/* ======== STEP 3: ANNUAL FEE & PAYMENT ======== */}
        {step === 3 && (
          <div className="animate-fade-in">
            <div className="space-y-6">
              <div className="border-b pb-4">
                <label className="block text-sm font-semibold mb-2">
                  Annual Fee (IDR)
                </label>
                <input
                  value="458,000"
                  disabled
                  className="w-full bg-gray-100 border border-gray-300 text-gray-700 py-2 px-3 rounded font-bold cursor-not-allowed"
                />
              </div>

              <div className="border-b pb-4">
                <p className="text-sm font-semibold mb-2">
                  A little contribution for a cup of coffee (IDR)
                </p>
                <div className="flex flex-wrap gap-4">
                  {["0", "2k", "5k", "20k", "50k", "100k"].map((val) => (
                    <label
                      key={val}
                      className="flex items-center gap-2 cursor-pointer border p-2 rounded hover:bg-orange-50"
                    >
                      <input
                        type="radio"
                        name="coffeeContribution"
                        value={val}
                        onChange={handleChange}
                        checked={formData.coffeeContribution === val}
                        className="accent-orange-500"
                      />
                      {val}
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold mb-2">
                  Payment Method *
                </label>
                <select
                  name="paymentMethod"
                  value={formData.paymentMethod}
                  onChange={handleChange}
                  className="border p-3 rounded w-full bg-white"
                >
                  <option value="paypal">Paypal</option>
                  <option value="BRI virtual account">
                    BRI Virtual Account
                  </option>
                  <option value="BNI virtual account">
                    BNI Virtual Account
                  </option>
                  <option value="bank mandiri virtual account">
                    Bank Mandiri Virtual Account
                  </option>
                  <option value="bank permata virtual account">
                    Bank Permata Virtual Account
                  </option>
                </select>
              </div>

              <div className="flex items-start gap-2 mt-6 p-4 bg-orange-50 border border-orange-200 rounded">
                <input
                  type="checkbox"
                  required
                  className="mt-1 cursor-pointer accent-orange-500 w-5 h-5"
                />
                <span className="text-sm text-gray-700">
                  I have read the agreement and accept it. By clicking Register,
                  you agree to our terms and conditions.
                </span>
              </div>
            </div>
          </div>
        )}

        {/* ======== TOMBOL NAVIGASI ======== */}
        <div className="flex justify-between mt-8 pt-6">
          {step > 1 ? (
            <button
              type="button"
              onClick={prevStep}
              className="px-6 py-2 border border-orange-500 text-orange-500 rounded font-bold hover:bg-orange-50 transition-colors"
            >
              Back
            </button>
          ) : (
            <div></div> /* Biar tombol Next tetap rata kanan */
          )}

          {step < 3 ? (
            <button
              type="submit"
              className="px-8 py-2 bg-orange-500 text-white rounded font-bold hover:bg-orange-600 transition-colors shadow"
            >
              Next Step
            </button>
          ) : (
            <button
              type="submit"
              className="px-8 py-2 bg-green-600 text-white rounded font-bold hover:bg-green-700 transition-colors shadow"
            >
              REGISTER & INVOICE
            </button>
          )}
        </div>
      </form>
    </div>
  );
}
